import { SearchProvider } from "./context/SearchContext"
import { UserProvider } from "./context/UserContext"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <UserProvider>
            <SearchProvider>
              {children}
            </SearchProvider>
          </UserProvider>
          
          {/*
          searchProvider bọc cái children lại để children có thể use các value mà Provider cung cấp
          */}
      </body>

    </html>
  )
}
